### ISSUE TITLE
Needed data 

### ISSUE THREAD

**Issue by longwindwang1** [huskar51121/software#2]
What kind of data would need to add into database? 

Which cols should to be connected? 

where to collect data?
: Kaggle

**Comment by huskar51121** [comment]
This is my preliminary idea:

There are four classes in total:
User information (including payment)
Travel information (GPS data, including the corresponding user ID for the trip)
Building Facility Information
Administrator Information

What is specific to each class can be discussed with team members, but most of the content should have no objections

The connection should have:
User information (including payment), itinerary information (GPS data), connected through user ID

A small amount of data can be input through the front-end, while a large amount of data can be directly generated through scripts and placed in the database
